"""
Django settings for srinikethan_website project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ

# Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Reading .env file
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '0.0.0.0', '*'])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'srinikethan_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'portfolio' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'srinikethan_website.wsgi.application'


# Database - Azure SQL Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': env('DB_NAME'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='1433'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Jazzmin Admin UI ──────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    # Top-left branding
    'site_title': 'Content Manager',
    'site_header': 'Srinikethan',
    'site_brand': 'Srinikethan',
    'welcome_sign': 'Welcome to your Content Manager',
    'copyright': 'Srinikethan',

    # Single search box in top bar
    'search_model': ['portfolio.BlogPost'],

    # User avatar in top-bar
    'user_avatar': None,

    # ── Top navigation links ──────────────────────────────────────────────
    'topmenu_links': [
        {'name': 'View Website', 'url': '/', 'new_window': True},
        {'model': 'portfolio.Contact'},
    ],

    # ── User avatar dropdown (alongside Change Password & Logout) ─────────
    'usermenu_links': [
        {'name': 'Two-Factor Authentication', 'url': '/account/two_factor/', 'new_window': False, 'icon': 'fas fa-shield-alt'},
    ],

    # ── Left sidebar navigation (grouped & ordered) ───────────────────────
    'show_sidebar': True,
    'navigation_expanded': True,
    # Hide OTP/2FA technical apps – not needed in the content manager sidebar.
    # Auth is shown here; SuperuserOnlyAdmin hides it from non-superusers.
    'hide_apps': ['otp_static', 'otp_totp', 'two_factor'],
    'hide_models': [],
    'order_with_respect_to': [
        'portfolio',
        # — Page settings —
        'portfolio.HomePage',
        'portfolio.MyStory',
        'portfolio.ServicesPage',
        'portfolio.InsightsPage',
        'portfolio.BlogPage',
        'portfolio.SiteSettings',
        # — Content items —
        'portfolio.BlogPost',
        'portfolio.Service',
        'portfolio.Program',
        'portfolio.Testimonial',
        'portfolio.Workshop',
        # — Inbox —
        'portfolio.Contact',
        # — Admin (superuser only) —
        'auth',
        'auth.user',
        'auth.Group',
    ],
    'icons': {
        'auth': 'fas fa-user-shield',
        'auth.user': 'fas fa-user-cog',
        'auth.Group': 'fas fa-users',
        # Page-level models
        'portfolio': 'fas fa-globe',
        'portfolio.HomePage': 'fas fa-home',
        'portfolio.MyStory': 'fas fa-user-circle',
        'portfolio.ServicesPage': 'fas fa-briefcase',
        'portfolio.InsightsPage': 'fas fa-lightbulb',
        'portfolio.BlogPage': 'fas fa-newspaper',
        'portfolio.SiteSettings': 'fas fa-sliders-h',
        # Content item models
        'portfolio.BlogPost': 'fas fa-pen-alt',
        'portfolio.Service': 'fas fa-concierge-bell',
        'portfolio.Program': 'fas fa-graduation-cap',
        'portfolio.Testimonial': 'fas fa-star',
        'portfolio.Workshop': 'fas fa-chalkboard-teacher',
        'portfolio.Contact': 'fas fa-inbox',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',

    # ── Related modal popups ──────────────────────────────────────────────
    'related_modal_active': False,

    # ── Custom CSS/JS ─────────────────────────────────────────────────────
    'custom_css': 'css/admin_custom.css',
    'custom_js': None,
    'use_google_fonts_cdn': True,
    'show_ui_builder': False,

    # ── Change view ───────────────────────────────────────────────────────
    'changeform_format': 'collapsible',
    'changeform_format_overrides': {
        'auth.user': 'collapsible',
        'auth.group': 'collapsible',
    },
    'language_chooser': False,
}

JAZZMIN_UI_TWEAKS = {
    # Navbar
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-primary',
    'accent': 'accent-primary',
    'navbar': 'navbar-dark',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': True,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'default',
    'dark_mode_theme': None,
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
    'actions_sticky_top': True,
}

# ── Two-Factor Authentication ─────────────────────────────────────────────────
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = '/account/post-login/'
TWO_FACTOR_REMEMBER_COOKIE_AGE = 60 * 60 * 24 * 30   # 30 days
