# Generated by Django 5.2.11 on 2026-02-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_title', models.CharField(default='Your Financial Growth Partner', help_text='Main title displayed in the welcome banner', max_length=200)),
                ('welcome_subtitle', models.TextField(default='Empowering you to achieve financial independence through smart planning and strategic growth.', help_text='Subtitle text under the welcome title')),
                ('profile_photo', models.ImageField(blank=True, help_text='Profile photo displayed in the welcome banner', null=True, upload_to='homepage/')),
                ('philosophy_title', models.CharField(default='My Philosophy', help_text='Title for the philosophy section', max_length=200)),
                ('philosophy_subtitle', models.CharField(default="Building wealth is not about luck—it's about having the right strategy, consistent execution, and a trusted guide.", help_text='Philosophy subtitle', max_length=300)),
                ('philosophy_highlight_1', models.CharField(default='Personalized Strategies', max_length=100)),
                ('philosophy_highlight_2', models.CharField(default='Data-Driven Insights', max_length=100)),
                ('philosophy_highlight_3', models.CharField(default='Long-term Success', max_length=100)),
                ('philosophy_highlight_4', models.CharField(default='Continuous Support', max_length=100)),
                ('expertise_title', models.CharField(default='Expertise Areas', help_text='Title for the expertise section', max_length=200)),
                ('expertise_subtitle', models.TextField(default='Comprehensive financial solutions tailored to your unique goals and circumstances.', help_text='Subtitle for expertise section')),
                ('success_stories_title', models.CharField(default='Success Stories', help_text='Title for success stories section', max_length=200)),
                ('success_stories_subtitle', models.TextField(default='Real transformations from clients who trusted the journey.', help_text='Subtitle for success stories section')),
                ('knowledge_hub_title', models.CharField(default='Knowledge Hub', help_text='Title for knowledge hub section', max_length=200)),
                ('knowledge_hub_subtitle', models.TextField(default='Latest insights, strategies, and market perspectives to keep you informed.', help_text='Subtitle for knowledge hub section')),
                ('primary_cta_text', models.CharField(default='Start Your Journey', max_length=50)),
                ('primary_cta_url', models.CharField(default='/connect/', max_length=200)),
                ('secondary_cta_text', models.CharField(default='Explore Expertise', max_length=50)),
                ('secondary_cta_url', models.CharField(default='#expertise', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='MyStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='My Story', help_text='Main page title', max_length=200)),
                ('page_subtitle', models.TextField(default="Every great journey begins with a single step. Here's how my passion for financial empowerment began.", help_text='Page subtitle/introduction')),
                ('intro_text', models.TextField(default="My path to becoming a financial growth partner wasn't traditional, but it was authentic. Each chapter of my life has shaped my understanding of what it truly means to achieve financial independence.", help_text='Introduction text for the story')),
                ('chapter_1_number', models.CharField(default='01', max_length=10)),
                ('chapter_1_title', models.CharField(default='Early Foundation', max_length=100)),
                ('chapter_1_period', models.CharField(default='2010-2014', max_length=50)),
                ('chapter_1_content', models.TextField(default='Started my journey understanding the basics of personal finance and investment principles.', help_text='Content for chapter 1')),
                ('chapter_2_number', models.CharField(default='02', max_length=10)),
                ('chapter_2_title', models.CharField(default='Professional Growth', max_length=100)),
                ('chapter_2_period', models.CharField(default='2015-2018', max_length=50)),
                ('chapter_2_content', models.TextField(default='Developed expertise in financial planning while helping others achieve their goals.', help_text='Content for chapter 2')),
                ('chapter_3_number', models.CharField(default='03', max_length=10)),
                ('chapter_3_title', models.CharField(default='Market Expertise', max_length=100)),
                ('chapter_3_period', models.CharField(default='2019-2022', max_length=50)),
                ('chapter_3_content', models.TextField(default='Navigated market volatility and economic challenges, refining strategies for sustainable growth.', help_text='Content for chapter 3')),
                ('chapter_4_number', models.CharField(default='04', max_length=10)),
                ('chapter_4_title', models.CharField(default='Today & Beyond', max_length=100)),
                ('chapter_4_period', models.CharField(default='2023-Present', max_length=50)),
                ('chapter_4_content', models.TextField(default='Continuing to innovate and guide clients toward financial independence with proven strategies.', help_text='Content for chapter 4')),
                ('mission_title', models.CharField(default='Mission & Vision', help_text='Title for mission section', max_length=200)),
                ('mission_text', models.TextField(default='My mission is simple: to democratize financial growth and make wealth-building strategies accessible to everyone, regardless of their starting point.', help_text='Mission statement text')),
                ('personal_note', models.TextField(default="When I'm not analyzing markets or developing strategies, you'll find me reading, traveling, or exploring new technologies that can enhance financial planning.", help_text='Personal note to add authenticity')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'My Story Content',
                'verbose_name_plural': 'My Story Content',
            },
        ),
    ]
