# Generated by Django 5.2.11 on 2026-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_homepage_mystory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Financial Insights', help_text='Main page title', max_length=200)),
                ('page_subtitle', models.TextField(default='Expert analysis, market trends, and strategic insights to enhance your financial journey.', help_text='Page subtitle/introduction')),
                ('hero_title', models.CharField(default='Navigate Markets with Confidence', help_text='Main hero section title', max_length=300)),
                ('hero_description', models.TextField(default='Stay ahead of market trends with expert analysis, actionable insights, and proven strategies that drive real financial growth.', help_text='Hero section description')),
                ('featured_title', models.CharField(default='Market Outlook 2024', help_text='Featured insight title', max_length=200)),
                ('featured_excerpt', models.TextField(default='Understanding the key economic indicators and investment opportunities that will shape the financial landscape this year.', help_text='Featured insight excerpt')),
                ('featured_content', models.TextField(default='The financial markets are experiencing unprecedented shifts...', help_text='Full content for featured insight')),
                ('featured_image_alt', models.CharField(default='Market analysis chart', help_text='Alt text for featured image', max_length=200)),
                ('quick_insights_title', models.CharField(default='Quick Market Insights', help_text='Title for quick insights section', max_length=200)),
                ('insight_1_title', models.CharField(default='Diversification Strategies', help_text='First quick insight title', max_length=150)),
                ('insight_1_content', models.TextField(default='Learn how to spread risk across different asset classes for more stable long-term returns.', help_text='First quick insight content')),
                ('insight_2_title', models.CharField(default='Tax Optimization Tips', help_text='Second quick insight title', max_length=150)),
                ('insight_2_content', models.TextField(default='Maximize your after-tax returns with strategic planning and smart investment timing.', help_text='Second quick insight content')),
                ('insight_3_title', models.CharField(default='Economic Indicators', help_text='Third quick insight title', max_length=150)),
                ('insight_3_content', models.TextField(default='Key metrics to watch that signal market direction and investment opportunities.', help_text='Third quick insight content')),
                ('insight_4_title', models.CharField(default='Risk Management', help_text='Fourth quick insight title', max_length=150)),
                ('insight_4_content', models.TextField(default='Protect your portfolio with proven risk assessment and mitigation strategies.', help_text='Fourth quick insight content')),
                ('newsletter_title', models.CharField(default='Stay Updated', help_text='Newsletter signup section title', max_length=200)),
                ('newsletter_description', models.TextField(default='Get weekly insights delivered to your inbox. Market analysis, investment tips, and exclusive strategies.', help_text='Newsletter signup description')),
                ('cta_title', models.CharField(default='Ready to Apply These Insights?', help_text='Call to action title', max_length=200)),
                ('cta_description', models.TextField(default="Transform market knowledge into personal wealth. Let's discuss your financial strategy.", help_text='Call to action description')),
                ('cta_button_text', models.CharField(default='Schedule Consultation', help_text='CTA button text', max_length=50)),
                ('cta_button_url', models.CharField(default='/contact/', help_text='CTA button URL', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insights Page Content',
                'verbose_name_plural': 'Insights Page Content',
            },
        ),
    ]
