# Generated by Django 5.2.11 on 2026-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_insightspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_label', models.CharField(default='Insights Library', help_text='Label shown above the blog title', max_length=100)),
                ('page_title', models.CharField(default='Blog', help_text='Main blog page title', max_length=200)),
                ('page_subtitle', models.TextField(default='Latest thoughts, perspectives, and articles from the field.', help_text='Blog page subtitle/introduction')),
                ('featured_posts_title', models.CharField(default='Featured Articles', help_text='Title for featured posts', max_length=200)),
                ('featured_posts_subtitle', models.CharField(default='Selected highlights from the latest financial thinking', help_text='Subtitle for featured posts', max_length=250)),
                ('all_posts_title', models.CharField(default='All Articles', help_text='Title for the full post list', max_length=200)),
                ('all_posts_subtitle', models.CharField(default='Browse the latest articles and commentary', help_text='Subtitle for the full post list', max_length=250)),
                ('cta_title', models.CharField(default='Keep Exploring', help_text='Call to action title', max_length=200)),
                ('cta_description', models.TextField(default='If you want deeper guidance, connect for a direct conversation about your goals.', help_text='Call to action description')),
                ('cta_button_text', models.CharField(default='Schedule Consultation', help_text='Call to action button text', max_length=50)),
                ('cta_button_url', models.CharField(default='/contact/', help_text='Call to action button URL', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Page Content',
                'verbose_name_plural': 'Blog Page Content',
            },
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_label', models.CharField(default='Professional Services', help_text='Label shown above the page title', max_length=100)),
                ('page_title', models.CharField(default='Wealth Management Expertise', help_text='Main page title', max_length=200)),
                ('page_subtitle', models.TextField(default='Comprehensive financial solutions designed to grow, protect, and preserve your wealth across generations.', help_text='Page subtitle/introduction')),
                ('core_services_title', models.CharField(default='Core Wealth Management Services', help_text='Title for the core services section', max_length=200)),
                ('core_services_subtitle', models.CharField(default='Strategic financial planning with personalized solutions for your unique goals', help_text='Subtitle for the core services section', max_length=250)),
                ('specialized_title', models.CharField(default='Specialized Wealth Solutions', help_text='Title for the specialized services section', max_length=200)),
                ('specialized_subtitle', models.CharField(default='Advanced strategies for high-net-worth individuals and complex financial situations', help_text='Subtitle for the specialized services section', max_length=250)),
                ('process_title', models.CharField(default='Our Wealth Management Process', help_text='Title for the process section', max_length=200)),
                ('process_subtitle', models.CharField(default='A systematic approach to building and preserving your wealth', help_text='Subtitle for the process section', max_length=250)),
                ('cta_title', models.CharField(default='Ready to Transform Your Financial Future?', help_text='Call to action title', max_length=200)),
                ('cta_description', models.TextField(default='Schedule a confidential consultation to discuss your wealth management needs and discover how we can help you achieve your financial goals.', help_text='Call to action description')),
                ('cta_primary_text', models.CharField(default='Schedule Consultation', help_text='Primary call-to-action text', max_length=50)),
                ('cta_secondary_text', models.CharField(default='Learn About Our Approach', help_text='Secondary call-to-action text', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Page Content',
                'verbose_name_plural': 'Services Page Content',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='expertise_label',
            field=models.CharField(default='What I Offer', help_text='Small label above the expertise section title', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journeys_label',
            field=models.CharField(default='Transform Your Future', help_text='Label above the financial journeys section', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journeys_subtitle',
            field=models.CharField(default='Choose the path that aligns with your aspirations and timeline', help_text='Subtitle for the financial journeys section', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journeys_title',
            field=models.CharField(default='Financial Growth Journeys', help_text='Title for the financial journeys section', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='knowledge_hub_label',
            field=models.CharField(default='Stay Informed', help_text='Label shown above the knowledge hub section title', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='scroll_prompt_text',
            field=models.CharField(default='Explore Journey', help_text='Prompt shown below the hero section', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_label',
            field=models.CharField(default="Hi, I'm", help_text='Small greeting label shown in the hero section', max_length=50),
        ),
        migrations.AddField(
            model_name='insightspage',
            name='latest_articles_subtitle',
            field=models.CharField(default='Stay informed with our newest insights and analysis', help_text='Subtitle for the latest articles section', max_length=250),
        ),
        migrations.AddField(
            model_name='insightspage',
            name='latest_articles_title',
            field=models.CharField(default='Latest Articles', help_text='Title for the latest articles section', max_length=200),
        ),
        migrations.AddField(
            model_name='insightspage',
            name='quick_insights_subtitle',
            field=models.CharField(default='Actionable insights to enhance your financial strategy', help_text='Subtitle for quick insights section', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='primary_cta_url',
            field=models.CharField(default='/contact/', max_length=200),
        ),
    ]
